#!/bin/sh
set -eu
if [ "${1:-}" = configure ]; then
    if [ -x /usr/bin/systemctl ]; then
        /usr/bin/systemctl --global enable scambio.service
    fi
    if [ -x /usr/bin/gtk-update-icon-cache ]; then
        /usr/bin/gtk-update-icon-cache -q -t /usr/share/icons/hicolor
    fi
fi
