"""Replaceable adapter boundaries; no transport types leak into the policy."""

from collections.abc import Callable
from typing import Protocol

from scambio.config import Config
from scambio.core.policy import Event

Emit = Callable[[Event], None]
Done = Callable[[], None]


class BluetoothPort(Protocol):
    name: str
    connected: bool
    ready: bool

    def start(self) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def close(self) -> None: ...
    def reload(self, config: Config) -> None: ...


class AudioPort(Protocol):
    ready: bool

    def start(self) -> None: ...
    def route(self, done: Done) -> None: ...
    def restore(self, done: Done) -> None: ...
    def close(self) -> None: ...
    def reload(self, config: Config) -> None: ...


class SessionPort(Protocol):
    ready: bool

    def start(self) -> None: ...
    def release_inhibitor(self) -> None: ...
    def close(self) -> None: ...
    def reload(self, config: Config) -> None: ...
